services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3090:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3091
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started
    environment:
      DB_HOST: db
      DB_USER: damuser
      DB_PASSWORD: dampassword
      DB_NAME: jewelrydam
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniopassword
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "sleep 5 && npm run start"
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: jewelrydam
      MYSQL_USER: damuser
      MYSQL_PASSWORD: dampassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "damuser", "-pdampassword"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - app-network

volumes:
  db_data:
  minio_data:

networks:
  app-network:
    driver: bridge
