version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3090:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:3091
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3091:3091"
    depends_on:
      - db
      - minio
    environment:
      DB_HOST: db
      DB_USER: damuser
      DB_PASSWORD: dampassword
      DB_NAME: jewelrydam
      MINIO_ENDPOINT: minio
      MINIO_ACCESS_KEY: miniouser
      MINIO_SECRET_KEY: miniopassword
    command: ["sh", "-c", "sleep 3600"]  # Keep the container running for debugging
    networks:
      - app-network

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: jewelrydam
      MYSQL_USER: damuser
      MYSQL_PASSWORD: dampassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - app-network

volumes:
  db_data:
  minio_data:

networks:
  app-network:
    driver: bridge
