FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

# Install the MySQL client
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

COPY . ./

EXPOSE 3091

CMD ["npm", "run", "start"]